[tool.poetry]
name = "ambr-py"
version = "0.1.5"
description = "API wrapper for ambr.top written in Python"
authors = ["seriaati <seria.ati@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
packages = [{include = "ambr"}]

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.8.6"
pydantic = "^2.4.2"
diskcache = "^5.6.3"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
